source "http://rubygems.org"
gem "nmatrix", :path => "../nmatrix"
gem "gsl", :path => "../rb-gsl"
gem "distribution", :path => "../distribution"
gem "rspec-core"
gem "rspec"
gem "pry"
gem "rake"
gem "rake-compiler"
gem "statsample"
gem "ruby-progressbar"
gem "rbtree"
gem "rubyvis"
